name: Go

on:
  push:
    branches: [ "2024-update" ]
  pull_request:
    branches: [ "2024-update" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go version
