name: Github_Action_Test

on:
  push:
    branches: [ "2024-update" ]
  pull_request:
    branches: [ "feature" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Show go version
      run: go version

    - name: Run single feature test
      run: go run app/up/*.go ngo task -d ./tests/functests -t feature-demo.yml -i dev --configdir=./tests/functests

    - name: Run individual feature request test
      run: |
        . ./funcs.rc
        uptestx c0001
        
        
